language: php

php:
    - 7.1
    - 7.2

env:
    coverage=on
    phpstan=on

matrix:
    allow_failures:
        - php: 7.2

script:
    - vendor/bin/tester tests -s $coverageArgs
    - php temp/code-checker/src/code-checker.php --short-arrays --strict-types
    - php temp/coding-standard/vendor/symplify/easy-coding-standard/bin/ecs check src tests --config temp/coding-standard/coding-standard-php71.neon
    - if [ "$phpstan" = "on" ]; then php vendor/phpstan/phpstan-shim/phpstan.phar analyse --ansi --no-progress -l7 -c phpstan.neon src tests/tests; fi

before_script:
    - if [ "$phpstan" = "on" ]; then composer require --dev --no-update phpstan/phpstan-shim:^0.7; fi
    - travis_retry composer install --no-interaction --prefer-dist
    - travis_retry composer create-project nette/code-checker temp/code-checker ~2 --no-interaction
    - travis_retry composer create-project nette/coding-standard temp/coding-standard --no-progress
    - if [ "$coverage" == "on" ]; then coverageArgs="-p phpdbg --coverage ./coverage.xml --coverage-src ./src"; fi

after_script:
    - >
      if [ "$coverage" == "on" ]; then
      wget https://github.com/satooshi/php-coveralls/releases/download/v1.0.1/coveralls.phar
      && php coveralls.phar --verbose --config tests/.coveralls.yml
      || true; fi

after_failure:
    - for i in $(find ./tests -name \*.expected); do echo "--- $i"; cat $i; echo; echo; done
    - for i in $(find ./tests -name \*.actual); do echo "--- $i"; cat $i; echo; echo; done

sudo: false
