name: Tests

on:
    pull_request: null
    push:
        branches:
            - master

jobs:
    tests:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                php: ['7.3', '7.3']
                node: ['0', '1']

        name: PHP ${{ matrix.php }} tests ${{ matrix.node }}
        steps:
            -   uses: actions/checkout@v2

            -   shell: bash
                run: mkdir -p temp && find tests/Tests -name '*.phpt' > temp/testFiles.txt

            -   shell: bash
                run: cat temp/testFiles.txt

            -   shell: bash
                run: wc -l temp/testFiles.txt

            -   uses: shivammathur/setup-php@v1
                with:
                    php-version: ${{ matrix.php }}
                    coverage: none
            -   run: composer install --no-progress --prefer-dist
            -   run: composer run-script tests

    lowest_dependencies:
        runs-on: ubuntu-latest
        steps:
            -   uses: actions/checkout@v2
            -   uses: shivammathur/setup-php@v1
                with:
                    php-version: 7.1
                    coverage: none
            -   run: composer update --no-progress --prefer-dist --prefer-lowest --prefer-stable
            -   run: composer run-script tests
