name: PHPStan

on:
    pull_request: null
    push:
        branches:
            - master

jobs:
    phpstan:
        runs-on: ubuntu-latest
        steps:
            -   uses: actions/checkout@v2
            -   uses: shivammathur/setup-php@v1
                with:
                    php-version: 7.3
                    coverage: none
            -   run: composer update --no-progress --prefer-dist --prefer-lowest --prefer-stable
            -   run: composer run-script phpstan-install
            -   run: composer run-script phpstan
